
/*
    This file is part of "ChoiCo" a web application for designing digital games, written by Marianthi Grizioti for the National and Kapodistrian University of Athens (Educational Technology Lab).
    Copyright (C) 2017-2018.
    ChoiCo is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    ChoiCo is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
*/
english = {
		name: "English",
	introText : "Welcome to ChoiCo ",
	introSubText : "A kit for designing and playing digital games",
	designModeText : "Design Mode",
	playModeText : "Play Mode",
	designButtonSrc : "media/imgs/design.png",
	playButtonSrc : "media/imgs/playgame.png",
	openYourFile : "Open Your File",
	onlineExamples : "Online Examples",
	tab1: "Game Interface",
	tab2: "Initial Settings",
	tab3: "Gameplay Rules",
	tab4: "End Rules",
	uploadImgDisc : "Change Background",
	addPointDisc: "Add Point",
	addInstructionsDisc: "Add game instructions",
	deleteIcoDisc : "Delete selected attribute",
	settingsIcoDisc : "Settings of selected attribute",
	addAttributeDisc : "Add Attribute",
	pointsLimitTxt : "Max No of Turns",
	manualDisc : "User Manual",
	contactDisc : "Contact Form",
	homeDisc : "Back to homepage",
	generalErrorMessage: "There is an error in the code. Open the game in design mode to fix it. ",
	variableErrorMessageA: "Ooops: There is no game field called ",
		variableErrorMessageB: ". Remove or replace this variable in the tab: ",
	tab1Message : "Please check that the game settings are correct, by opening the tab Initial Settings (2nd tab)",
	tab3Message: "You have not set any ending conditions on the tab 'End Rules'. The game will never end! Are you sure you want to go to Play Mode?",
	markersMessage : "You have not insert any points on your map. Are you sure you want to go to Play Mode?",
	layersRemoveMessage: "Are you sure you want to remove this layer?",
	homeMessage : "ATTENTION: By going to homepage, all your current progress will be lost! Go to homepage?",
	typeLabel : "Attribute Type",
	visibilityLabel : "Visibility to player",
	envyText : "Game for sustainability and environmental ethics ",
	perfectVilleText: " Game for a citizen's choices in a city ",
	perfectVilleGame: "location.href += '?perfectVilleEng';",
	shoppingGame: "location.href += '?shoppingEng';",
	badiText: " Game for balanced diet ",
	 mpText: " Game for ancient Greek ",
	 supermarketText: " Game for mathematical relations  ",
	 covideText: "A game about Covid-19 Pandemic",
	 //pcText: " Game for computer architecture ",
	 composteText: " Game for chemistry and recycling ",
	 ethicsText : " Game for work ethic",
	 eatingTextHB : "A half-baked game about healthy food choices",
	 eatingText: "A game about healthy food choices",
	 eatingOutHBGame: "location.href += '?eatingOutHBEng';",
 chefText: "A half-baked game about Computational Thinking and business managment",
 chefGame: "location.href += '?CTChefEng';",
 schoolText: "A mod of the game 'Eating Out', created by students ",
 europeText: "A mod of the game 'Eating Out', created by students ",
  europe: "location.href += '?europe';" ,
	  school:  "location.href += '?school';",
		eatingOutGame:  "location.href += '?eatingOutEng';",
	covidGame:  "location.href += '?covid19survivor';",
	envyGame:"location.href += '?envyCityEng';" ,
 manualUrl: "http://etl.ppp.uoa.gr/choico/manuals/choico_user_manual_EN.pdf",
	//PLAYMODE
	pointInfoText : "Point Information",
			gameStartedText : "The game has started",
			gameValues: "Game Values",
		pointsVisited: "No of Choices",
	selectButton : "Select Point",
	gameStatusText: "Game Status",
	deletePointText : "Delete Point",
	popUpMessage : "Game Ends! You have reached the maximum number of points <br>",
	gameInstructionsDefault: "Game Instructions: Click on a point to see its consequences on the info point table. Click 'select point' to select it. Your score is shown on the 'game values' table",
	selBoxText: "Text",
	selBoxNum: "Number",
	selBoxUrl: "Url",
	selBoxDate: "Date",
	selBoxImage: "Image",
	visBoxVisible: "Visible",
	visBoxHidden: "Hidden"
}

greek = {
	name: "Greek",
	introText : "Καλωσήρθατε στο ChoiCo",
	introSubText : "Σχεδιάστε και παίξτε τα δικά σας ψηφιακά παιχνίδια",
	designModeText : "Λειτουργία Σχεδιασμού",
	playModeText : "Λειτουργία Παιχνιδιού",
	designButtonSrc : "media/imgs/designGr.png",
	playButtonSrc : "media/imgs/playgameGr.png",
	openYourFile : "Άνοιγμα Αρχείου",
	onlineExamples : "Διαδικτυακά Παραδείγματα",
	tab1: "Διεπαφή Παιχνιδιού",
	tab2: "Αρχικές Ρυθμίσεις",
	tab3: "Κανόνες Ροής",
	tab4: "Κανόνες Τερματισμού",
	uploadImgDisc : "Αλλαγή Υποβάθρου",
	addPointDisc: "Προσθήκη Σημείου",
	addInstructionsDisc: "Προσθήκη οδηγιών παιχνιδιού",
	deleteIcoDisc : "Διαγραφή επιλεγμένου πεδίου",
	settingsIcoDisc : "Ρυθμίσεις επιλεγμένου πεδίου",
	addAttributeDisc : "Προσθήκη Πεδίου",
	pointsLimitTxt : "Μέγιστο Όριο Κινήσεων",
	manualDisc : "Εγχειρίδιο Χρήσης",
	contactDisc : "Φόρμα Επικοινωνίας",
	homeDisc : "Επιστροφή στην Αρχική Σελίδα",
 manualUrl: "http://etl.ppp.uoa.gr/choico/manuals/choico_user_manual_GR.pdf",
 	generalErrorMessage: "Υπάρχει το παρακάτω σφάλμα στον κώδικα! Άνοιξε το παιχνίδι σε λειτουργία σχεδιασμού για να το διορθώσεις. ",
	variableErrorMessageA: "Ooops: Δεν υπάρχει πεδίο με το όνομα: ",
		variableErrorMessageB: "Διέγραψε ή αντικατέστησε αυτή τη μεταβλητή στην καρτέλα: ",
	tab1Message : "Άνοιξε την καρτέλα 'Αρχικές Ρυθμίσεις' για να επιβεβαιώσεις ότι οι αρχικές τιμές είναι σωστές",
	tab3Message : "Δεν έχεις ορίσει κανόνες τερματισμού (καρτέλα 4). Το παιχνίδι δεν θα τερματίζει ποτέ! Σίγουρα θέλεις να προχωρήσεις;",
	markersMessage : "Δεν έχεις εισάγει κανένα σημείο στη σκηνή του παιχνιδιού.Σίγουρα θέλεις να προχωρήσεις;",
layersRemoveMessage: "Είστε βέβαιοι ότι θέλετε να διαγράψετε αυτό το layer;",
	homeMessage : "ΠΡΟΣΟΧΗ: Πηγαίνοντας στην αρχικη σελίδα θα χαθεί το παιχνίδι που σχεδιάσατε! Συνέχεια στην αρχική σελίδα;",
	typeLabel : "Τύπος Πεδίου",
	visibilityLabel : "Ορατό στον παίκτη",
	envyText : " Παιχνίδι για την αιεοφρεία και την περιβαλλοντική συνείδηση. ",
	perfectVilleText: " Παιχνίδι για τις επιλογές ενός πολίτη στην πόλη του ",
		perfectVilleGame: "location.href += '?perfectVilleGr';",
		shoppingGame: "location.href += '?shoppingGr';",
		eatingOutGame: "location.href += '?eatingOutGr';",
	badiText: " Παιχνίδι για την ισορροπημένη διατροφή ",
	 mpText: " Παιχνίδι γα τα αρχαία ελληνικά  ",
	 supermarketText: " Παιχνίδι μαθηματικών σχέσεων  ",
	  covideText: "Παιχνίδι για την πανδημία του Covid-19",
	 //pcText: " Παιχνίδι αρχιτεκτονικής υπολογιστών ",
	 composteText: " Παιχνίδι χημείας και περιβαλλοντικής ",
	  ethicsText : " Παιχνίδι γα την επαγγελματική ηθική ",
		eatingTextHB: "Μισοψημένο παιχνίδι για την ισορροπημένη διατροφή",
		eatingText: "Παιχνίδι για την ισορροπημένη διατροφή",
		envyGame: "location.href += '?envyCityGr';",
			covidGame:  "location.href += '?covid19survivorGR';",
			  eatingOutHBGame: "location.href += '?eatingOutHBGr';",
chefText: "Μισοψημένο παιχνίδι για την Υπολογιστική Σκέψη και τη διαχείρηση επιχερήσεων",
chefGame: "location.href += '?CTChefGr';",
schoolText: "Διασκευή μαθητών του παιχνιδιού 'Eating Out'",
europeText: "Διασκευή μαθητών του παιχνιδιού 'Eating Out'",
	//PLAY MODE
	pointInfoText : "Πληροφορίες Σημείου",
		gameStartedText : "Το παιχνίδι ξεκίνησε",
	gameValues: "Τιμές",
	pointsVisited: "Αριθμός Επιλογών",
	selectButton : "Επιλογή Σημείου",
	gameStatusText : "Κατάσταση Παιχνιδιού",
	deletePointText : "Διαγραφή Σημείου",
	popUpMessage : "Τέλος Παιχνιδιού! Έφτασες το μέγιστο όριο των επιτρεπόμενων κινήσεων <br>",
	gameInstructionsDefault : " Οδηγίες Παιχνιδιού: Κάνε κλίκ σε ένα σημείο για να δεις τις επιπτώσεις του στον πίνακα 'Πλρηοφοριές σημείου'. Μετά,κάνε κλικ στο κουμπί 'επιλογή σημείου' αν θέλεις να το επιλέξεις. Οι τιμές των παραμέτρων του παιχνιδιού αναγράφονται στον πίνακα 'Τιμές' πάνω από την περιοχή παιχνιδιού.",
	selBoxText: "Κείμενο",
	selBoxNum: "Αριθμός",
	selBoxUrl: "Σύνδεσμος",
	selBoxImage: "Εικόνα",
		selBoxDate: "Ημερομηνία",
	visBoxVisible: "Ορατό",
	visBoxHidden: "Κρυμμένο"
}
